import {StyleSheet} from 'react-native';
import {
  PRIMARY_COLOR,
  TEXT_COLOR_PRIMARY,
  TEXT_COLOR_SECONDARY,
  TEXT_COLOR_TERTIARY,
} from '../../../../contants/colors';

const saleDetailsStyles = StyleSheet.create({
  loaderContainer: {
    display: 'flex',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  header: {
    display: 'flex',
    flexDirection: 'row',
    paddingVertical: 20,
    paddingHorizontal: 20,
    gap: 20,
    width: '100%',
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'black',
    display: 'flex',
    flex: 1,
  },
  subtitle: {
    fontSize: 20,
    color: 'black',
    marginHorizontal: 20,
    fontWeight: 'bold',
  },
  textPrimary: {
    fontSize: 24,
    fontWeight: 'bold',
    color: PRIMARY_COLOR,
  },
  textSecondary: {
    fontSize: 18,
    fontWeight: 'bold',
    color: TEXT_COLOR_PRIMARY,
  },
  textTertiary: {
    fontSize: 16,
    fontWeight: 'bold',
    color: TEXT_COLOR_TERTIARY,
  },
  textPrimaryInverse: {
    fontSize: 24,
    fontWeight: 'bold',
    color: TEXT_COLOR_SECONDARY,
  },
  textTertiaryInverse: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'lightsteelblue',
  },
  mapImg: {
    width: 100,
    height: 100,
    borderRadius: 20,
    backgroundColor: 'grey',
  },
  select: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    borderRadius: 10,
    backgroundColor: 'lightgrey',
    marginBottom: 10,
  },
  mapContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
    padding: 10,
    width: '100%',
    height: '100%',
    backgroundColor: 'white',
    borderBottomStartRadius: 40,
    borderBottomEndRadius: 40,
    borderRadius: 20,
  },
  map: {
    display: 'flex',
    flex: 1,
    height: 200,
    borderRadius: 20,
    backgroundColor: 'grey',
  },
  modalMap: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    gap: 10,
    padding: 20,
    backgroundColor: 'transparent',
    borderRadius: 20,
    width: '100%',
    height: '90%',
  },
  closeMap: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    backgroundColor: '#dc3545',
    borderRadius: 10,
  },
  titleContainer: {
    display: 'flex',
    gap: 0,
    flex: 1,
  },
  personalInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    borderColor: 'blue',
    width: '100%',
    marginBottom: 26,
  },
  personalInfoItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
    paddingHorizontal: 20,
    borderColor: 'black',
    width: '100%',
  },
  productoItem: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: 'lightgrey',
    marginBottom: 5,
  },
  productoItemPrice: {
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
    width: 100,
  },
  productItemName: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'black',
    width: '80%',
  },
  telContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  telInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: 0,
  },
  telActions: {
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
  },
  telButton: {
    display: 'flex',
    width: 45,
    height: 45,
    borderRadius: 10,
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  telPhone: {
    backgroundColor: 'lightblue',
  },
  telWhatsapp: {
    backgroundColor: 'lightgreen',
  },
  results: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    gap: 10,
    backgroundColor: PRIMARY_COLOR,
    width: '100%',
    borderTopStartRadius: 40,
    borderTopEndRadius: 40,
    // padding: 16,
    height: 130,
    paddingBottom: 35,
  },
  resultItem: {
    display: 'flex',
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    paddingHorizontal: 16,
    borderColor: 'green',
    // marginBottom: 35,
  },
  resultItemIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    // backgroundColor: `#7ba1ff7a`,
    backgroundColor: `#4e76ce`,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saleInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    width: '100%',
    paddingVertical: 30,
    borderTopStartRadius: 40,
    borderTopEndRadius: 40,
    marginTop: -35,
    backgroundColor: 'white',
  },
  addPaymentButton: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    width: '90%',
    backgroundColor: PRIMARY_COLOR,
    borderRadius: 10,
    marginHorizontal: 20,
    marginBottom: 20,
  },
  alertPayment: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    width: '90%',
    backgroundColor: '#fde8e8',
    borderRadius: 10,
    marginHorizontal: 20,
    marginBottom: 20,
    fontSize: 18,
    color: '#9b1c1c',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  addVisitaButton: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    width: '90%',
    backgroundColor: '#198754',
    borderRadius: 10,
    marginHorizontal: 20,
    marginBottom: 20,
  },
  addPaymentButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  addPayModalContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  addPayModal: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    padding: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    width: '90%',
  },
  addPayModalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: 'black',
    marginBottom: 20,
  },
  addPayModalInput: {
    padding: 10,
    borderWidth: 1,
    borderColor: 'lightgrey',
    textAlignVertical: 'top',
    borderRadius: 10,
    marginBottom: 10,
    color: 'black',
    fontSize: 24,
  },
  addNotaModalInput: {
    padding: 10,
    borderWidth: 1,
    borderColor: 'lightgrey',
    textAlignVertical: 'top',
    borderRadius: 10,
    marginBottom: 10,
    color: 'black',
    fontSize: 24,
    height: 150,
  },
  addPayModalButton: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    backgroundColor: PRIMARY_COLOR,
    borderRadius: 10,
  },
  addPayModalButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  addPayModalClose: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    backgroundColor: 'lightgrey',
    borderRadius: 10,
  },
  addPayModalCloseText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  addCondonacionButton: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 10,
    width: '90%',
    backgroundColor: '#dc3545',
    borderRadius: 10,
    marginHorizontal: 20,
    marginBottom: 20,
  },
  payments: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    width: '100%',
    paddingVertical: 30,
    borderTopStartRadius: 40,
    borderTopEndRadius: 40,
    backgroundColor: 'white',
  },
  paymentItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: 'lightgrey',
  },
});

export default saleDetailsStyles;
